
command:
  - ${env}
  - python3
  - ./src/train_cifar.py
  - ${args}
  - --device
  - "cuda:0"

method: bayes
metric:
  goal: maximize
  name: valid_accuracy01
parameters:
  lr:
    values: [0.05, 0.1]
  momentum:
    values: [0.8, 0.9]
  gamma:
    values: [0.1, 0.2]
  batch-size:
    values: [32, 64, 128]
